export interface StrategySpec {
  id: number;
  name: string;
  originalName: string;
  category: 'Direcional' | 'Precisão' | 'Arbitragem';
  bias: 'ALTA' | 'BAIXA' | 'LATERAL' | 'VOLATILIDADE';
  difficulty: 'Iniciante' | 'Intermediário' | 'Avançado';
  whenToUse: string;
  riskReward: string;
  legsDescription: string;
  vegaPosture?: 'SHORT_VEGA' | 'LONG_VEGA' | 'VEGA_NEUTRAL';
  thetaPosture?: 'POSITIVE_THETA' | 'NEGATIVE_THETA';
  minIvRank?: number;
  maxIvRank?: number;
  minVrp?: number;
  idealGexRegime?: '+GEX' | '-GEX' | 'ANY';
  targetDteRange?: string;
  lifecycleRule?: string;
}

export const CME_STRATEGIES: StrategySpec[] = [
  { id: 1, name: 'Trava de Alta com Call', originalName: 'Bull Call Spread', category: 'Direcional', bias: 'ALTA', difficulty: 'Iniciante', whenToUse: 'Alta moderada com controle estrito de risco e custo reduzido.', riskReward: 'Risco Limitado / Retorno Limitado', legsDescription: 'Compra Call Strike A + Venda Call Strike B (A < B)', vegaPosture: 'VEGA_NEUTRAL', thetaPosture: 'NEGATIVE_THETA', idealGexRegime: 'ANY', targetDteRange: '21 a 45 DTE' },
  { id: 2, name: 'Trava de Baixa com Put', originalName: 'Bear Put Spread', category: 'Direcional', bias: 'BAIXA', difficulty: 'Iniciante', whenToUse: 'Baixa moderada com proteção contra volatilidade excessiva.', riskReward: 'Risco Limitado / Retorno Limitado', legsDescription: 'Compra Put Strike B + Venda Put Strike A (A < B)', vegaPosture: 'VEGA_NEUTRAL', thetaPosture: 'NEGATIVE_THETA', idealGexRegime: '-GEX', targetDteRange: '14 a 30 DTE' },
  { id: 3, name: 'Compra a Seco de Call', originalName: 'Long Call', category: 'Direcional', bias: 'ALTA', difficulty: 'Iniciante', whenToUse: 'Forte convicção de alta explosiva com risco limitado ao prêmio pago.', riskReward: 'Risco Limitado / Retorno Ilimitado', legsDescription: 'Compra Call OTM/ATM', vegaPosture: 'LONG_VEGA', thetaPosture: 'NEGATIVE_THETA', maxIvRank: 30, targetDteRange: '30 a 60 DTE' },
  { id: 4, name: 'Compra a Seco de Put', originalName: 'Long Put', category: 'Direcional', bias: 'BAIXA', difficulty: 'Iniciante', whenToUse: 'Queda acentuada ou hedge direcional da carteira de ações.', riskReward: 'Risco Limitado / Retorno Substancial', legsDescription: 'Compra Put OTM/ATM', vegaPosture: 'LONG_VEGA', thetaPosture: 'NEGATIVE_THETA', maxIvRank: 30, targetDteRange: '14 a 45 DTE' },
  { id: 5, name: 'Venda Coberta de Call', originalName: 'Covered Call', category: 'Precisão', bias: 'LATERAL', difficulty: 'Iniciante', whenToUse: 'Geração recorrente de renda em ações em custódia.', riskReward: 'Risco da Ação / Retorno Limitado ao Prêmio', legsDescription: 'Compra Ação + Venda Call OTM', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 40, targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar com 50% do lucro ou rolar aos 21 DTE' },
  { id: 6, name: 'Trava de Alta com Put a Crédito', originalName: 'Bull Put Spread', category: 'Direcional', bias: 'ALTA', difficulty: 'Intermediário', whenToUse: 'Mercado neutro a altista buscando coleta de prêmio com proteção.', riskReward: 'Risco Limitado à Asa / Retorno ao Crédito', legsDescription: 'Venda Put Strike B + Compra Put Strike A (A < B)', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 50, idealGexRegime: '+GEX', targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar com 50% do lucro ou aos 21 DTE' },
  { id: 7, name: 'Trava de Baixa com Call a Crédito', originalName: 'Bear Call Spread', category: 'Direcional', bias: 'BAIXA', difficulty: 'Intermediário', whenToUse: 'Mercado neutro a baixista com coleta de teta positivo.', riskReward: 'Risco Limitado à Asa / Retorno ao Crédito', legsDescription: 'Venda Call Strike A + Compra Call Strike B (A < B)', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 50, idealGexRegime: 'ANY', targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar com 50% do lucro ou aos 21 DTE' },
  { id: 8, name: 'Straddle Comprado', originalName: 'Long Straddle', category: 'Arbitragem', bias: 'VOLATILIDADE', difficulty: 'Intermediário', whenToUse: 'Expectativa de forte rompimento direcional antes de balanços ou FOMC.', riskReward: 'Risco Limitado aos Prêmios / Retorno Ilimitado', legsDescription: 'Compra Call ATM + Compra Put ATM', vegaPosture: 'LONG_VEGA', thetaPosture: 'NEGATIVE_THETA', maxIvRank: 30, targetDteRange: '14 a 30 DTE' },
  { id: 9, name: 'Strangle Comprado', originalName: 'Long Strangle', category: 'Arbitragem', bias: 'VOLATILIDADE', difficulty: 'Intermediário', whenToUse: 'Explosão de volatilidade com custo menor que o straddle.', riskReward: 'Risco Limitado / Retorno Ilimitado', legsDescription: 'Compra Call OTM + Compra Put OTM', vegaPosture: 'LONG_VEGA', thetaPosture: 'NEGATIVE_THETA', maxIvRank: 25, targetDteRange: '21 a 45 DTE' },
  { id: 10, name: 'Borboleta Longa com Calls', originalName: 'Long Call Butterfly', category: 'Precisão', bias: 'LATERAL', difficulty: 'Intermediário', whenToUse: 'Previsão de estagnação de preço em um strike central exato no vencimento.', riskReward: 'Risco Mínimo / Alto Retorno sobre Risco', legsDescription: 'Compra 1 Call A + Venda 2 Calls B + Compra 1 Call C', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', targetDteRange: '14 a 28 DTE' },
  { id: 11, name: 'Borboleta Longa com Puts', originalName: 'Long Put Butterfly', category: 'Precisão', bias: 'LATERAL', difficulty: 'Intermediário', whenToUse: 'Alvo de preço central via pernas de Put com baixo custo.', riskReward: 'Risco Mínimo / Retorno Elevado no Ponto Central', legsDescription: 'Compra 1 Put A + Venda 2 Puts B + Compra 1 Put C', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', targetDteRange: '14 a 28 DTE' },
  { id: 12, name: 'Iron Butterfly a Crédito', originalName: 'Iron Butterfly', category: 'Precisão', bias: 'LATERAL', difficulty: 'Intermediário', whenToUse: 'Coleta de alto prêmio com expectativa de baixa volatilidade.', riskReward: 'Risco Limitado / Crédito Retido no Strike Médio', legsDescription: 'Compra Put A + Venda Put B + Venda Call B + Compra Call C', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 60, targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar com 25% a 50% do lucro ou aos 21 DTE' },
  { id: 13, name: 'Condor Longo com Calls', originalName: 'Long Call Condor', category: 'Precisão', bias: 'LATERAL', difficulty: 'Intermediário', whenToUse: 'Túnel de consolidação com 4 strikes equidistantes.', riskReward: 'Risco Limitado / Retorno Máximo no Platô', legsDescription: 'Compra Call A + Venda Call B + Venda Call C + Compra Call D', vegaPosture: 'VEGA_NEUTRAL', thetaPosture: 'POSITIVE_THETA', targetDteRange: '21 a 35 DTE' },
  { id: 14, name: 'Trava de Linha / Calendário', originalName: 'Calendar Spread', category: 'Arbitragem', bias: 'LATERAL', difficulty: 'Avançado', whenToUse: 'Exploração do decaimento acelerado de teta da ponta curta vs longa.', riskReward: 'Risco Limitado ao Débito / Retorno no Decay', legsDescription: 'Venda Opção Vencimento Curto + Compra Opção Longa', vegaPosture: 'LONG_VEGA', thetaPosture: 'POSITIVE_THETA', maxIvRank: 35, targetDteRange: 'Curta: 21-30d / Longa: 60-90d' },
  { id: 15, name: 'Trava Diagonal', originalName: 'Diagonal Spread', category: 'Arbitragem', bias: 'ALTA', difficulty: 'Avançado', whenToUse: 'Substituto dinâmico de venda coberta com custo de capital reduzido.', riskReward: 'Risco Limitado / Renda Recorrente', legsDescription: 'Venda Opção Curta OTM + Compra Opção Longa ITM', vegaPosture: 'LONG_VEGA', thetaPosture: 'POSITIVE_THETA', targetDteRange: 'Curta: 30d / Longa: 90-180d' },
  { id: 16, name: 'Collar Protetor', originalName: 'Collar Protection', category: 'Precisão', bias: 'LATERAL', difficulty: 'Iniciante', whenToUse: 'Blindagem total de uma posição em ações a custo zero ou mínimo.', riskReward: 'Perda Bloqueada / Ganho Limitado à Call', legsDescription: 'Ação em Carteira + Compra Put OTM + Venda Call OTM', vegaPosture: 'VEGA_NEUTRAL', thetaPosture: 'NEGATIVE_THETA', targetDteRange: '60 a 120 DTE' },
  { id: 17, name: 'Ratio Call Spread', originalName: 'Call Ratio Spread', category: 'Direcional', bias: 'ALTA', difficulty: 'Avançado', whenToUse: 'Alta moderada até o strike vendido com custo zero ou crédito.', riskReward: 'Risco Superior / Lucro no Strike Vendido', legsDescription: 'Compra 1 Call A + Venda 2 Calls B (A < B)', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 50, targetDteRange: '30 a 45 DTE' },
  { id: 18, name: 'Ratio Put Spread', originalName: 'Put Ratio Spread', category: 'Direcional', bias: 'BAIXA', difficulty: 'Avançado', whenToUse: 'Queda moderada com financiamento da perna longa.', riskReward: 'Risco Inferior / Lucro no Strike Vendido', legsDescription: 'Compra 1 Put B + Venda 2 Puts A (A < B)', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 50, targetDteRange: '30 a 45 DTE' },
  { id: 19, name: 'Seagull de Alta', originalName: 'Bull Seagull', category: 'Precisão', bias: 'ALTA', difficulty: 'Avançado', whenToUse: 'Financiamento de trava de alta com venda de put fora do dinheiro.', riskReward: 'Risco na Put Vendida / Trava Gratuita', legsDescription: 'Venda Put OTM + Compra Call ATM + Venda Call OTM', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 45, targetDteRange: '30 a 60 DTE' },
  { id: 20, name: 'Iron Condor a Crédito', originalName: 'Iron Condor', category: 'Precisão', bias: 'LATERAL', difficulty: 'Intermediário', whenToUse: 'Estratégia rainha da renda quantitativa: lucrar com a passagem do tempo enquanto a ação oscilar dentro das Walls de OI/GEX.', riskReward: 'Risco Limitado às Asas / Retorno 100% do Crédito', legsDescription: 'Compra Put A + Venda Put B + Venda Call C + Compra Call D', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 50, minVrp: 4.0, idealGexRegime: '+GEX', targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar com 50% do lucro (ou 25% em condors estreitos) e encerrar impreterivelmente aos 21 DTE' },
  { id: 21, name: 'Reverse Iron Condor', originalName: 'Reverse Iron Condor', category: 'Arbitragem', bias: 'VOLATILIDADE', difficulty: 'Intermediário', whenToUse: 'Forte rompimento para qualquer um dos lados fora do túnel.', riskReward: 'Risco Limitado ao Débito / Retorno no Rompimento', legsDescription: 'Venda Put A + Compra Put B + Compra Call C + Venda Call D', vegaPosture: 'LONG_VEGA', thetaPosture: 'NEGATIVE_THETA', maxIvRank: 30, targetDteRange: '14 a 30 DTE' },
  { id: 22, name: 'Jade Lizard', originalName: 'Jade Lizard', category: 'Precisão', bias: 'LATERAL', difficulty: 'Avançado', whenToUse: 'Coleta de crédito sem risco de alta (crédito maior que a asa da call).', riskReward: 'Zero Risco na Alta / Risco Definido na Put', legsDescription: 'Venda Put OTM + Venda Call OTM + Compra Call OTM+', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 55, targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar com 50% do lucro ou aos 21 DTE' },
  { id: 23, name: 'Big Lizard', originalName: 'Big Lizard', category: 'Precisão', bias: 'LATERAL', difficulty: 'Avançado', whenToUse: 'Versão ATM do Jade Lizard com maior crédito coletado.', riskReward: 'Zero Risco na Alta / Ponto de Equilíbrio Amplo', legsDescription: 'Venda Straddle ATM + Compra Call OTM', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 65, targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar com 50% do lucro ou aos 21 DTE' },
  { id: 24, name: 'Guts Comprado', originalName: 'Long Guts', category: 'Arbitragem', bias: 'VOLATILIDADE', difficulty: 'Avançado', whenToUse: 'Explosão de volatilidade com opções profundamente dentro do dinheiro.', riskReward: 'Risco do Valor Extrínseco / Retorno no Delta', legsDescription: 'Compra Call ITM + Compra Put ITM', vegaPosture: 'LONG_VEGA', thetaPosture: 'NEGATIVE_THETA', maxIvRank: 25, targetDteRange: '14 a 30 DTE' },
  { id: 25, name: 'Box Spread de Arbitragem', originalName: 'Box Spread Arbitrage', category: 'Arbitragem', bias: 'LATERAL', difficulty: 'Avançado', whenToUse: 'Empréstimo sintético ou extração de taxa livre de risco implícita (somente em SPX europeu).', riskReward: 'Risco Zero em Europeia (Proibido em Americanas)', legsDescription: 'Bull Call Spread + Bear Put Spread nos mesmos strikes', vegaPosture: 'VEGA_NEUTRAL', thetaPosture: 'POSITIVE_THETA', targetDteRange: '30 a 180 DTE' },
  // EXPANSÃO ESCOPO INSTITUCIONAL TASTYTRADE (§6 e §8 da skill analista-senior-opcoes-us)
  { id: 26, name: 'Short Strangle (Δ16/Δ16)', originalName: 'Short Strangle', category: 'Precisão', bias: 'LATERAL', difficulty: 'Avançado', whenToUse: 'Setup nuclear do playbook mecânico da Tastytrade: venda de Put delta 16 + Call delta 16 com alto IV Rank e liquidez de topo.', riskReward: 'Risco Indefinido / Retorno do Crédito Líquido', legsDescription: 'Venda Put OTM (Δ ~16) + Venda Call OTM (Δ ~16)', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 50, minVrp: 5.0, idealGexRegime: '+GEX', targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar rigorosamente com 50% do crédito; rolar untested side no máx 1x; defender aos 21 DTE' },
  { id: 27, name: 'Short Straddle (ATM Crush)', originalName: 'Short Straddle', category: 'Precisão', bias: 'LATERAL', difficulty: 'Avançado', whenToUse: 'Captura imediata de colapso de volatilidade extrema com máximo Theta Decay.', riskReward: 'Risco Indefinido / Retorno do Crédito Máximo', legsDescription: 'Venda Call ATM + Venda Put ATM', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 70, minVrp: 10.0, idealGexRegime: '+GEX', targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar com 25% a 50% do lucro rápido; gestão ativa' },
  { id: 28, name: 'Double Calendar Spread', originalName: 'Double Calendar', category: 'Arbitragem', bias: 'LATERAL', difficulty: 'Avançado', whenToUse: 'Consolidação em canal amplo com volatilidade na mínima histórica (Contango limpo). Perfil de lucro mais largo que o calendário simples.', riskReward: 'Risco Limitado ao Débito / Retorno no Plateau Duplo', legsDescription: 'Calendar Spread de Put abaixo do spot + Calendar Spread de Call acima do spot', vegaPosture: 'LONG_VEGA', thetaPosture: 'POSITIVE_THETA', maxIvRank: 30, idealGexRegime: '+GEX', targetDteRange: 'Curta: 21-30d / Longa: 60-90d', lifecycleRule: 'Encerrar antes do vencimento da perna curta' },
  { id: 29, name: 'Reverse Calendar Spread', originalName: 'Reverse Calendar', category: 'Arbitragem', bias: 'VOLATILIDADE', difficulty: 'Avançado', whenToUse: 'Exploração de backwardation extrema pré-evento: compra de opção curta contra venda de opção longa.', riskReward: 'Risco Limitado / Retorno na Expansão Curta', legsDescription: 'Compra Opção Curta + Venda Opção Longa mesmo strike', vegaPosture: 'SHORT_VEGA', thetaPosture: 'NEGATIVE_THETA', minIvRank: 65, targetDteRange: 'Curta: 7-14d / Longa: 45-60d' },
  { id: 30, name: 'Broken-Wing Butterfly', originalName: 'Broken-Wing Butterfly', category: 'Precisão', bias: 'ALTA', difficulty: 'Avançado', whenToUse: 'Montagem de borboleta assimétrica com crédito inicial ou custo zero, eliminando o risco em uma das pontas.', riskReward: 'Zero Risco em um Lado / Risco Definido no Outro', legsDescription: 'Compra 1 Opção A + Venda 2 Opções B + Compra 1 Opção D (larguras assimétricas)', vegaPosture: 'SHORT_VEGA', thetaPosture: 'POSITIVE_THETA', minIvRank: 45, targetDteRange: '30 a 45 DTE', lifecycleRule: 'Fechar com 50% do lucro ou aos 21 DTE' },
  { id: 31, name: "Poor Man's Covered Call (PMCC)", originalName: "Poor Man's Covered Call", category: 'Direcional', bias: 'ALTA', difficulty: 'Intermediário', whenToUse: 'Substituto de compra de ações com 70% menos capital: Call longa profunda ITM (delta 80) + Venda recorrente de Calls curtas OTM (delta 30).', riskReward: 'Risco do Débito da LEAP / Renda Recorrente de Theta', legsDescription: 'Compra Call LEAP ITM (Δ ~80, 90-180 DTE) + Venda Call OTM (Δ ~30, 30 DTE)', vegaPosture: 'LONG_VEGA', thetaPosture: 'POSITIVE_THETA', targetDteRange: 'Curta: 30 DTE / Longa: 90-180 DTE', lifecycleRule: 'Rolar a curta aos 21 DTE; vigiar risco de dividendo na curta' },
  { id: 32, name: 'Double Diagonal Spread', originalName: 'Double Diagonal', category: 'Arbitragem', bias: 'LATERAL', difficulty: 'Avançado', whenToUse: 'Versão dinâmica do Iron Condor com expirações diferentes: vende asas curtas para theta acelerado e compra asas longas para vega protegido.', riskReward: 'Risco Definido / Retorno Superior no Túnel', legsDescription: 'Diagonal de Put + Diagonal de Call (curtas vendidas, longas compradas)', vegaPosture: 'LONG_VEGA', thetaPosture: 'POSITIVE_THETA', maxIvRank: 40, targetDteRange: 'Curtas: 30 DTE / Longas: 60-90 DTE' },
];

// Alias para compatibilidade retroativa absoluta com código existente
export const CME_25_STRATEGIES = CME_STRATEGIES;